### ISSUE TITLE
Two bugs in ignore method

### ISSUE THREAD

**Issue by mahmoud-syr** [simplify9/FluentOlap#1]
Dear Simplify9 team,
This is Mahmoud from PostaPlus. I was working on your `FluentOlap` project in order to understand the internals of the source code. After few tests I have found what I think is two bugs in the source code. 
Considering the following entities:

```
    public class Shipper
    {
        public string Name { get; set; }
        public string OriginCountry { get; set; }
    }
    public class Phone
    {
        public string Number { get; set; }
    }
    public class Supplier
    {
        public string Name { get; set; }
        public string DestinationCountry { get; set; }
        public Phone Phone { get; set; }
        public Phone Phone2 { get; set; }
    }
    public class Parcel2Level
    {
        public string Id { get; set; }
        public int Location { get; set; }
        public int Count { get; set; }

        public Shipper Shipper { get; set; }
        public Supplier Supplier { get; set; }

    }
```

And the following Analysis object:

```
    public class Parcel2LevelDefault : AnalyticalObject<Parcel2Level>
    {
        public Parcel2LevelDefault()
        {
            Property(p => p.Supplier).Ignore(p => p.Phone);
            Property(p => p.Shipper).Ignore(p => p.Name);
        }
    }
```

### Exepcted
To ignore the `Name` property in the `Shipper` reference in the `Parcel2Level`.
To ignore only the `Phone` complex property in the `Supplier` reference in the `Parcel2Level`.

### Actual
The `Name` property can still be found in the Analysis object `TypeMap`
Both `Phone` and `Phone2` properties both get removed from the `TypeMap`

### Explanation
1. `Name` Property didn't get removed due to the fact that in case we are trying to ignore nested primitive type property, the dictionary remove method called with a key of only the property and its direct parent name, whereas based on the current architecture we need the full path to that property.
2. `Phone` and `Phone2` properties both get removed from the `TypeMap` because in the current implementation of the ignore method all type maps with a name that **contains** the combination of _ignored property direct parent and property name_ are removed.

I apologies if this is not the standard/supported template for issues in Simplify9.

Kind Regards.

**Comment by shaheen-s9** [comment]
Fixed with the latest push.

New unit tests have been added to test the scenarios. 

Thank you for the extremely detailed issue!
