### ISSUE TITLE
Nullable property aren't handled gracefully in DataCollector class

### ISSUE THREAD

**Issue by mahmoud-syr** [simplify9/FluentOlap#11]
When you have a nullable property, it can have a null value and therefore it should be handled gracefully that is when the value is null the DataCollector shouldn't call the service because in that case one of the `required` parameters in the route is missing.
For example:
`https://localhost/api/corporateCustomers/1/` -> the route is of the form 'https://localhost/api/corporateCustomers/{tenantId}/{corporateCustomerId}' and the `corporateCustomerId` in the root object is null in this case which leave us with a malformed route value.

In the previous scenario, the `DataCollector` will try to hit the api anyway with that malformed route and thus will result in `404 error` a long with a malformed `json` result which will cause an exception to be thrown due to invalid json format when deserializing the result.

**Comment by shaheensarafa** [comment]
Updated the handling to skip over expansion when the expandable key value is null, please try now

**Comment by mahmoud-syr** [comment]
> Updated the handling to skip over expansion when the expandable key value is null, please try now

Thanks Shaheen for your support! But the latest commit didn't solve the issue.

```
JToken parsedRoot = JToken.Parse(rootResult.Raw);
if (!parsedRoot.HasValues)
{
    missingParam = true;
    continue;
}
```
Please note that the condition in that code block will always evaluate to true because it referee to the root object which will always have children nodes, our issue is with the `innerParam` value that might referee to a nullable property. So, my suggestion is to change the condition into something like this:
`if (string.IsNullOrWhiteSpace(parsedRoot[innerParam].Value<string>()))`

**Comment by shaheensarafa** [comment]
Took in your suggestion, and updated the conditional check

**Comment by shaheensarafa** [comment]
Please update me so I know whether or not to close the issue.

**Comment by mahmoud-syr** [comment]
Dear Shaheen, 
I can confirm it's working fine.
Thank you very much.
