### ISSUE TITLE
Timespan data type get expanded into time parts properties in the database

### ISSUE THREAD

**Issue by mahmoud-syr** [simplify9/FluentOlap#14]
I was able to reach the stage of creating the actual database table but I noticed that the property of type time span get expanded into it's internal properties like the picture below

![image](https://user-images.githubusercontent.com/65822550/102136645-f3e7d380-3e59-11eb-9978-9af3373e2117.png)

My suggestion is to consider the `TimeSpan` type just as `DateTime` type a primitive type and use it's string representation when storing it in the database.

**Comment by shaheensarafa** [comment]
Will be added in the next push, treating it as string.

**Comment by mahmoud-syr** [comment]
I think it would be better to use the DB-Engine specific data type representation of the C# `TimeSpan` for example MaraiDB has `Time` type. The same goes for Nvarchar instead of text, this is actually just a suggestion and it's not urgent. I prefer to have the solution runnable and the rest are just a matter of inhancement.

**Comment by shaheensarafa** [comment]
Will be included in the data types isue.
