### ISSUE TITLE
KeyNotFoundException: The given key was not present in the dictionary

### ISSUE THREAD

**Issue by mahmoud-syr** [simplify9/FluentOlap#17]
When expanding a custom property (using the string overload of `Property` method) where the value might be null and thus the expanded object might be null, and when that expanded object have transformation rules an exception of type `KeyNotFoundException` is thrown referring to the property which have the transformation rules defined.

Example:

Inside the root analytical object:

`Property("CurrentWorkflow", GenerateWorkflowAnalyticalObject()).GetFromService(Configs.Services.CurrentWorkflowByShipment, GenerateWorkflowAnalyticalObject());`

```
        private AnalyticalObject<WorkflowDt> GenerateWorkflowAnalyticalObject()
        {
            var workflow = new AnalyticalObject<WorkflowDt>();
            //workflow.Property(item => item.CreatedAt).HasTransformation(dt => ((DateTime)dt).ToString("yyyy-MM-dd HH:mm:ss"));
            //workflow.Property(item => item.UpdatedAt).HasTransformation(dt => ((DateTime?)dt)?.ToString("yyyy-MM-dd HH:mm:ss"));
            return workflow;
        }
```

The commented lines cause this exception to be thrown.

**Comment by shaheensarafa** [comment]
Is the exception thrown during the `PopulateAsync` call? If so, I'm pushing a null-handling fix in the next push to the dynamicTransformations branch. 

However, if this is thrown elsewhere, let me know :)

**Comment by shaheensarafa** [comment]
@mahmoud-syr  In the newest push, this is handled by the new Transformation API. Please take a look and close the issue if it is solved.

**Comment by mahmoud-syr** [comment]
Dear Shaheen, now I'm receiving null exceptions on all properties of object that can be null (individual customer as an example).
I think the transformation is still being executed even if the object is null.

**Comment by shaheensarafa** [comment]
Can you pull the latest from the branch and tell me at what line this error is being thrown, or give me a stack trace please? 

Much appreciated.

**Comment by shaheensarafa** [comment]
@mahmoud-syr please close the issue if it has been resolved.
