### ISSUE TITLE
Stackoverflow exception when trying to use type with DataTime property

### ISSUE THREAD

**Issue by mahmoud-syr** [simplify9/FluentOlap#2]
Given the following code
```
    public class NanoShipment
    {
        public DateTime CreationDate { get; set; }
    }
    public class WideNanoShipment : AnalyticalObject<NanoShipment>
    {

    }
```
And then trying to instantiate an object of the type `WideNanoShipment` 

### Exepcted
The object should be instantiated a long with its properties in the type map

### Actual
StackOverflow Exception is thrown

### Explanation
The `IsPrimitive` function will return false for a value of type `DateTime`, so the code will iterate through the `DateTime` object properties, one of which is `Date` which will return another value of type `DateTime`, and so on and so forth.

### Suggestion:
Using this code to check for `Primitivity` of a type. Taking into account that we are actually not interested in the fact that the type by itself is primitive, but rather in the `Primitivity` from the DB Engine's point.

```
    public static class TypeHelper
    {
        public static bool IsDBPrimitive<T>(T obj)
        {
            return IsDBPrimitive(typeof(T));
        }
        public static bool IsDBPrimitive(Type type)
        {
            if (Nullable.GetUnderlyingType(type) != null)
                return true;
            if (type == typeof(string))
                return true;
            else if (type == typeof(DateTime))
                return true;
            else if (type == typeof(decimal))
                return true;
            return type.IsPrimitive;
        }
    }
```

**Based on the CLR Primitive types are the ones that can be assigned a value using a literal, exceptions to this rule are string and decimal types.**

**Comment by shaheensarafa** [comment]
Fixed by making the "TryGuessInternalType" function a little smarter.
