### ISSUE TITLE
Nullable types are not handled

### ISSUE THREAD

**Issue by mahmoud-syr** [simplify9/FluentOlap#3]
Given the following code
```
    public class NanoShipment
    {
        public int? Cod { get; set; }
    }
    public class WideNanoShipment : AnalyticalObject<NanoShipment>
    {

    }
```
And then trying to instantiate an object of the type `WideNanoShipment` 

### Exepcted
The object should be instantiated a long with its properties in the type map

### Actual
Instead of the `Cod` property, two properties are found (`HasValue` and `Value`).

### Explanation
The `IsPrimitive` function will return false for any nullable type so the nullable type's properties instead will be listed.

**Comment by shaheensarafa** [comment]
Fixed by making TryGuessInternalType check for nullables.
