### ISSUE TITLE
Cannot use type with children property having the same type of the enclosing class

### ISSUE THREAD

**Issue by mahmoud-syr** [simplify9/FluentOlap#4]
Given the following code
```
    public class NanoShipment
    {
        public NanoShipment MainShipment { get; set; }
    }
    public class WideNanoShipment : AnalyticalObject<NanoShipment>
    {

    }
```
And then trying to instantiate an object of the type `WideNanoShipment` 

### Exepcted
The object should be instantiated a long with its properties in the type map.
Children of the Same type should be followed only once.

### Actual
StackOverflow Exception is thrown

### Explanation
The current implementation will follow the type's property types forever.

**Comment by shaheensarafa** [comment]
An implementation with dynamic depth levels allowed has been added. It still needs some cleaning up when it comes to analytical children referencing themselves, (key cleanup) but it now covers the use case.
