### ISSUE TITLE
[Suggestion] performance overhead of the current way Ignore is implemented

### ISSUE THREAD

**Issue by mahmoud-syr** [simplify9/FluentOlap#6]
**This is not an issue but rather a suggestion**
Currently ignore is done after scanning through the whole object properties and sub properties and filling the Type map dictionary but the problem is that we might have types of 20 or 30 columns some of which have complex types and in case of entity framework that number will be double in case of many foreign keys to other complex types (due to the fact that Entity Framework requires the existence of "Navigational properties" in order to understand the relationship in the schema) so my suggestion is that ignore `Rules` should be taken into account while generating the type properties.

**Comment by shaheensarafa** [comment]
I'm aware of the performance overhead of how ignore is implemented. 

However, the current implementation of InitTypeMap and how it is run in the constructor allows for a cleaner and simpler looking experience. (not needing to define any properties at all if the user is satisfied with the defaults)

Maybe in the future, Ignore rules can be added in the settings for FluentOlap along with things like the service definitions.

**Comment by shaheensarafa** [comment]
Added IgnoreAttribute, if a property has the [Ignore] attribute on it, it will be ignored during initialization.
